In [4]:
import pandas as pd
df = pd.read_excel("C:\Users\smc46\Desktop\Cleaning data.xlsx")
print df.head(5)

      id  Page1  state     district  Gender    AGE       Q4        Q5        \
0  31049      1        19       188         1        22         2         5
1  31040      1         8        52         1        23         1         3
2  31037      1        32       422         1        19         1         4
3  31035      1        27       310         1        25         1         7
4  31032      1        19       190         1        22         2         5

   Q6        Q7            ...        Q110_11       Q110_12       \
0         1       5.0      ...                 NaN           NaN
1        17       NaN      ...                 NaN           NaN
2         8       NaN      ...                 NaN           NaN
3         8       NaN      ...                 1.0           2.0
4         1       5.0      ...                 2.0           2.0

   Q110_13       Q110_14       Q110_15       Q110_16       Q110_17       \
0           NaN           NaN           NaN           NaN           NaN
1           NaN           NaN           NaN           NaN           NaN
2           NaN           NaN           NaN           NaN           NaN
3           2.0           2.0           2.0           2.0           2.0
4           2.0           2.0           2.0           2.0           2.0

   Q110_18       Q110_19       Page6 weightd
0           NaN           NaN            NaN
1           NaN           NaN            NaN
2           NaN           NaN            NaN
3           2.0           1.0       0.311626
4           2.0           2.0       0.144183

[5 rows x 506 columns]

In [6]:
printdf.sort(['Product','Sales'], ascending=[True, False])

NameError: name 'data' is not defined

In [16]:
x=df.loc[:,['Q6      ','Q7      ']]
print x

       Q6        Q7
0             1       5.0
1            17       NaN
2             8       NaN
3             8       NaN
4             1       5.0
5            17       7.0
6             1       6.0
7            15       NaN
8             1       7.0
9             8       NaN
10            1       6.0
11           11       NaN
12            6       NaN
13            1       6.0
14            5       7.0
15           13       NaN
16            1       3.0
17            6       NaN
18            3       NaN
19            1       NaN
20            1       5.0
21            1       7.0
22            5       6.0
23            1       7.0
24           17       NaN
25            7       NaN
26            1       5.0
27            2       NaN
28            1       NaN
29            1       NaN
...         ...       ...
10581         5       7.0
10582         1       NaN
10583         2       6.0
10584         1       NaN
10585         2       5.0
10586         3       6.0
10587         1       6.0
10588         1       4.0
10589         1       5.0
10590         1       NaN
10591         8       NaN
10592         1       NaN
10593         5       5.0
10594         5       7.0
10595         2       5.0
10596         8       NaN
10597         7       NaN
10598         8       NaN
10599         5       NaN
10600         7       NaN
10601         1       NaN
10602         1       NaN
10603         8       NaN
10604         2       6.0
10605        15       NaN
10606         7       NaN
10607         1       NaN
10608        15       3.0
10609         3       7.0
10610         1       7.0

[10611 rows x 2 columns]

In [10]:
data.loc[:['Gender  ']]

NameError: name 'data' is not defined

In [12]:
df.lc[:['Gender  ']]

TypeError: '['Gender  ']' is an invalid key

In [17]:
x.sort(['Q6      '], ascending=[True])

C:\Users\smc46\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

       Q6        Q7
0             1       5.0
6179          1       NaN
6178          1       NaN
6177          1       5.0
6175          1       NaN
6174          1       NaN
6172          1       7.0
6169          1       4.0
6168          1       NaN
6167          1       NaN
6166          1       NaN
6165          1       6.0
6164          1       3.0
6163          1       1.0
6180          1       5.0
6162          1       NaN
6157          1       7.0
6154          1       7.0
6153          1       7.0
6152          1       4.0
6150          1       NaN
6148          1       5.0
6145          1       7.0
6144          1       6.0
6142          1       NaN
6137          1       6.0
6136          1       NaN
6133          1       NaN
6132          1       NaN
6158          1       5.0
...         ...       ...
6488         19       NaN
7915         19       NaN
4403         19       3.0
4791         19       NaN
4191         19       NaN
4769         19       NaN
9080         19       4.0
8105         19       NaN
10187        19       NaN
8947         19       5.0
6729         19       4.0
2093         19       NaN
8712         19       NaN
9598         19       NaN
10517        19       NaN
10332        19       NaN
5874         19       NaN
10434        19       NaN
8395         19       NaN
3800         19       7.0
992          19       NaN
4647         19       NaN
1886         19       NaN
3286         19       7.0
9153         19       NaN
5371         19       NaN
6762         19       NaN
5121         19       NaN
7645         19       5.0
6549         19       NaN

[10611 rows x 2 columns]